### PR TITLE
Fix empty snapshot on certain devices

### LINKED ISSUE #923: MapView#snapshot returns a black bitmap
## Environment

This problem is raised in issue #42, And it has been repaired.
But I still have this bug, and it occurs every time.
Do I need an updated version?
```
  implementation 'com.mapbox.maps:android:10.1.0'
```
```
        btn_snapshot.setOnClickListener {
            mMapView?.snapshot {
                val bitmap = it
                runOnUiThread {
                    image_view.setImageBitmap(bitmap)
                }
            }
//            thread {
//                val bitmap = mMapView?.snapshot()
//                runOnUiThread {
//                    image_view.setImageBitmap(bitmap)
//                }
//            }
        }
```

### PR DESCRIPTION
**Pull request by yunikkk**
### Summary of changes

Previously reading pixels from GPU did not respect swap buffers moment. That led to blank snapshots on some devices (e.g. Huawei-s) since snapshot was taken after framebuffer which was purged after swapBuffers.
This PR fixes snapshot to always happen before `swapBuffers` is called.

## Pull request checklist:
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [x] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Optimize code for java consumption (`@JvmOverloads`, `@file:JvmName`, etc).
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [x] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [x] Add an entry inside this element for inclusion in the `mapbox-maps-android` changelog: `<changelog>Fixed black MapView#snapshot returned on some devices (e.g. Huawei).</changelog>`.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` firstly and then port to `v10.[version]` release branch.

Fixes: #923 

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).

### CODE REVIEW

File: sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt [hunk 1]
```diff
@@ -38,6 +39,8 @@ internal class MapboxRenderThread : Choreographer.FrameCallback {
   internal val renderEventQueue = CopyOnWriteArrayList<Runnable>()
   @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
   internal val eventQueue = CopyOnWriteArrayList<Runnable>()
+  @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+  internal var snapshotter: Runnable? = null
```
Comment (kiryldz) [inline sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt:43]: use better naming

File: sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt [hunk 2]
```diff
@@ -38,6 +39,8 @@ internal class MapboxRenderThread : Choreographer.FrameCallback {
   internal val renderEventQueue = CopyOnWriteArrayList<Runnable>()
   @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
   internal val eventQueue = CopyOnWriteArrayList<Runnable>()
+  @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
```
Comment (alexander-kulikovskii) [inline sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt:42]: will you add some tests?

**Review by tobrun — APPROVED** [review]
great work!

**Review by pengdev — APPROVED** [review]

File: app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt [hunk 3]
```diff
@@ -25,8 +25,11 @@ class MapViewSnapshotActivity : AppCompatActivity() {
     mapboxMap.loadStyleUri(Style.MAPBOX_STREETS)
 
     binding.fab.setOnClickListener {
-      val bitmap = binding.mapView.snapshot()
-      binding.imageView.setImageBitmap(bitmap)
+      binding.mapView.snapshot { bitmap ->
```
Comment (yunikkk) [inline app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt:28]: Used async version of snapshotter to avoid blocking main thread

File: sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt (hunk 2 above)
Comment (yunikkk) [reply sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt:41]: Added

File: sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt [hunk 4]
```diff
@@ -117,8 +117,7 @@ internal abstract class MapboxRenderer : MapClient {
     renderThread.queueEvent(runnable)
   }
 
-  @AnyThread
-  @Synchronized
+  @WorkerThread
```
Comment (yunikkk) [inline sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt:120]: Changed annotation to indicate that main thread shouldn't call this blocking version of snapshot

File: app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt (hunk 3 above)
Comment (kiryldz) [reply app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt:28]: very solid solution!

File: sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt (hunk 4 above)
Comment (kiryldz) [reply sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt:120]: good catch

File: sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt [hunk 5]
```diff
@@ -471,4 +471,56 @@ class MapboxRenderThreadTest {
...
+    every { runnable3.run() } answers { latch.countDown() }
+    Shadows.shadowOf(renderHandlerThread.handler?.looper).pause()
+    mapboxRenderThread.queueSnapshot(runnable)
+    mapboxRenderThread.queueSnapshot(runnable2)
+    mapboxRenderThread.queueSnapshot(runnable3)
+    Shadows.shadowOf(renderHandlerThread.handler?.looper).idle()
+    if (!latch.await(waitTime, TimeUnit.MILLISECONDS)) {
+      throw TimeoutException()
+    }
+    verify {
```
Comment (kiryldz) [inline sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt:520]: Guess we should also verify order here to make sure that 3 runnalbes are run in correct order and between `mapboxRenderer.onDrawFrame()` and `eglCore.swapBuffers(any())`. Perhaps we could even have one test instead of 2 then

Comment (yunikkk) [reply sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt:520]: Thought about it, I'm not really sure we should make such assumptions. Internally Thread could save those runnables unordered and call not in the order they were added

**Review by kiryldz — CHANGES_REQUESTED** [review]
Please fix other unit tests failing:
```
com.mapbox.maps.renderer.MapboxSurfaceHolderRendererTest > onSnapshotSuccessSync FAILED
    java.lang.AssertionError at VerifyingState.kt:66

com.mapbox.maps.renderer.MapboxSurfaceRendererTest > onSnapshotSuccessSync FAILED
    java.lang.AssertionError at VerifyingState.kt:66

com.mapbox.maps.renderer.MapboxTextureViewRendererTest > onSnapshotSuccessSync FAILED
    java.lang.AssertionError at VerifyingState.kt:66
```

File: sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt (hunk 5 above)
Comment (yunikkk) [reply sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt:520]: Also I believe it's a good practice to split checks and keep verifications as atomic as possible, tests are easier to support then

Comment (kiryldz) [reply sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt:520]: it's true when using well-written parametrized tests or smth similar
in this case tests are not greatly refactored and imho leaving one test verifying execution order of runnables + correct invocation time between core draw calls and swapping buffers is more reasonable

File: sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt [hunk 6]
```diff
@@ -471,4 +471,56 @@ class MapboxRenderThreadTest {
...
+  }
+
+  @Test
+  fun multipleSnapshotsAreTaken() {
+    val latch = CountDownLatch(3)
+    val surface = mockk<Surface>()
+    every { surface.isValid } returns true
+    every { eglCore.eglStatusSuccess } returns true
+    every { eglCore.createWindowSurface(any()) } returns mockk(relaxed = true)
+    mapboxRenderThread.onSurfaceCreated(surface, 1, 1)
```
Comment (alexander-kulikovskii) [inline sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt:505]: nit:
lines 501-505 and 478-482 can be moved to small function `mockSurface()`

File: sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt (hunk 5 above)
Comment (yunikkk) [reply sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt]: Discussed, refactored to single test

**Review by kiryldz — APPROVED** [review]
