### PR TITLE
Fix compass is not showing in "edge-to-edge" mode

### LINKED ISSUE #1295: Compass is not showing in "edge-to-edge" mode
## Environment

- Android OS version: 11
- Devices affected:  Pixel 5a
- Maps SDK Version: master

## Observed behavior and steps to reproduce

I'm following [Android's documentation to show an Activity edge-to-edge](https://developer.android.com/training/gestures/edge-to-edge#step_4_immersive_mode=) . This activity is hosting a `MapView`. However doing so causes the compass to disappear.

I start by taking this demo/sample app, then [make changes to show edge-to-edge](https://github.com/tir38/mapbox-maps-android/commit/fcde21364f1e6dfc8f343c8a7e038cfe3147a9c5)

You can see in this video that the Layout Inspector on the left still "sees" the CompassView++. But my phone, on the right, does not display the compass.

https://user-images.githubusercontent.com/1980553/164357122-f9d19d25-d0ed-43a4-b211-805f1ada8a63.mov

Just to be sure, [I update the compass margins](https://github.com/tir38/mapbox-maps-android/commit/191d609a2db9af9941372bce83371f351d286e72) to "push" the compass well within any display cutout. Still seeing the problem.

Then just for the heck of it, [I change the transparency on the status/nav bars](https://github.com/tir38/mapbox-maps-android/commit/289e6c6e67c4c01d08a0d9bfd59b07dd348ac504) and suddenly the compass reappears. 

https://user-images.githubusercontent.com/1980553/164357332-ce6ba2a7-b009-44e3-b9e4-53f84b37f13c.mov

I initially assumed this was caused by something in the Android Window code. But in the sample you can see the scale bar on the top left is not affected, even though it is at least as close to the window edge as the compass. So something specific must be happening with the compass.

You can experiment by grabbing my fork, building, and then launching the "Display the use's location" sample.

For comparison, here is a video of this sample app _without any changes_.

https://user-images.githubusercontent.com/1980553/164358055-136ba216-0af8-4e50-bb27-814307e8d8e4.mov

Things start getting real weird when you rotate and/or navigate away from the app.

https://user-images.githubusercontent.com/1980553/164362829-260df55d-2b98-47e3-abbf-b34dffec8898.mov

++ unrelated issue that Layout Inspector doesn't display the map itself

## Expected behavior

Compass should always show

### PR DESCRIPTION
**Pull request by Chaoba**
### Summary of changes
Fix #1295 

For some reason, in "edge-to-edge" mode compass will not show while turning visibility to `VISIBLE` from `INVISIBLE`. However, it works if we change the visibility to `GONE`.

## Pull request checklist:
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Optimize code for java consumption (`@JvmOverloads`, `@file:JvmName`, etc).
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Run `make update-api` to update generated api files, if there's public API changes, otherwise the `verify-api-*` CI steps might fail.
 - [x] Update [CHANGELOG.md](../CHANGELOG.md) or use the label 'skip changelog', otherwise `check changelog` CI step will fail.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` firstly and then port to `v10.[version]` release branch.

Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).

### CODE REVIEW

File: plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt [hunk 1]
```diff
@@ -52,7 +52,7 @@ open class CompassViewImpl
       visibility = if (value) {
         View.VISIBLE
       } else {
-        View.INVISIBLE
+        View.GONE
```
Comment (alexander-kulikovskii) [inline plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt:55]: should we cover such cases with tests?

Comment (Chaoba) [reply plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt:55]: Do you mean pixel match test?

**Review by pengdev — APPROVED** [review]
some tests would be great to have.

File: plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt (hunk 1 above)
Comment (Chaoba) [reply plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt:55]: As discussed online, will leave it as it is now since it's not easy to test.
